% This is an autogenerated sample test for file rockPaperScissors.m
classdef testrockPaperScissorsFinishCoverage < matlab.unittest.TestCase

    methods (Test)

        function testScissorsVsPaper(testCase)
            % Specify the input(s) of rockPaperScissors
            p1 = "scissors";
            p2 = "paper";

            % Specify the expected output(s) of rockPaperScissors
            expected_result = "Player 1 wins";

            % Exercise the function rockPaperScissors
            actual_result = rockPaperScissors(p1, p2);

            testCase.verifyEqual(actual_result, expected_result);
        end

        function testPapervsRock(testCase)
            % Specify the input(s) of rockPaperScissors
            p1 = "paper";
            p2 = "rock";

            % Specify the expected output(s) of rockPaperScissors
            expected_result = "Player 1 wins";

            % Exercise the function rockPaperScissors
            actual_result = rockPaperScissors(p1, p2);

            testCase.verifyEqual(actual_result, expected_result);
        end

        function testPapervsPaper(testCase)
            % Specify the input(s) of rockPaperScissors
            p1 = "paper";
            p2 = "paper";

            % Specify the expected output(s) of rockPaperScissors
            expected_result = "Player 1 wins";

            % Exercise the function rockPaperScissors
            actual_result = rockPaperScissors(p1, p2);

            testCase.verifyEqual(actual_result, expected_result);
        end
    end
end